apiVersion: v1
kind: Service
metadata:
  name: app-resource-service
  namespace: bladex
  labels:
    app: app-resource-service
spec:
  ports:
  - port: 8010
    targetPort: 8010
    protocol: TCP
  selector:
    app: app-resource-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-resource-service
  namespace: bladex
  labels:
    app: app-resource-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-resource-service
  template:
    metadata:
      labels:
        app: app-resource-service
    spec:
      #hostNetwork: true
      containers:
      - name: app-resource-pod
        image: 192.168.127.158:5000/app-resource-service:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PARAMES
          value: -Djava.security.egd=file:/dev/./urandom -Dspring.cloud.sentinel.transport.dashboard=192.168.127.137:38858 -Dspring.redis.host=192.168.127.137 -Dspring.redis.port=36379 -Dspring.cloud.nacos.discovery.server-addr=192.168.127.137:38848 -Dspring.cloud.nacos.config.server-addr=192.168.127.137:38848 -Dspring.datasource.username=root -Dspring.datasource.password=root -Dspring.datasource.url=jdbc:mysql://192.168.127.137:33306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 8010
        volumeMounts:
        - mountPath : /app/resource/logs
          name: log-vol
      volumes:
      - name: log-vol
        hostPath:
          path: /home/logs/blade-resource